accuracy: True

loss: False

numpy_files:
  - ./../experiments/lang-binary/output/lang_binary_gru
  - ./../experiments/lang-reshuffle/output/lang_reshuffle_gru_medium

config_files:
  - ./../experiments/lang-binary/configs/gru.yaml
  - ./../experiments/lang-reshuffle/configs/gru_medium.yaml

labels:
  "gru_binary_base" : "gru_binary"
  "gru_reshuffle_medium" : "gru_reshuffle"