accuracy: True

loss: True

numpy_files:
  - ./../experiments/mnist-reshuffle/output/mnist_reshuffle_mlp
  - ./../experiments/mnist-reshuffle/output/mnist_reshuffle_lstm

config_files:
  - ./../experiments/mnist-reshuffle/configs/mlp.yaml
  - ./../experiments/mnist-reshuffle/configs/lstm.yaml